endpoint: wss://rpc.ibp.network/polkadot
mock-signature-host: true
block: 22616108


db: ./db.sqlite
runtime-log-level: 5

import-storage:
  System:
    Account:
      - - - 12dbdz7jZAkCcCMbMiP3CXG3ZoSjVNvCgDJbuNr5MSV5swc2
        - providers: 1
          data:
            free: '98700000000000000000'
